# Generated by Django 4.1.5 on 2023-12-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ManyToManyField(blank=True, to='media.type'),
        ),
    ]
