# Generated by Django 4.1.5 on 2024-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_alter_post_options_remove_post_post_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ManyToManyField(blank=True, null=True, to='media.type'),
        ),
    ]
